ungrouped:
  hosts:
    192.168.43.170:
      ansible_user: root
      clients:
      - name: homeserver-restic
        ca: restic
        create_directories: true
        cert: /opt/container-secrets/restic-autobackup/ssl_cert.pem
        key: /opt/container-secrets/restic-autobackup/ssl_key.pem
        cacert: /opt/container-secrets/restic-autobackup/ca.pem
        combined: /opt/container-secrets/restic-autobackup/ssl_combined.pem
        common_name: homeserver
        owner: root
        group: root

      servers:
      - name: grafana
        ca: main
        create_directories: true
        cert: /opt/container-secrets/grafana/server.crt
        key: /opt/container-secrets/grafana/server.key
        cacert: /opt/container-secrets/grafana/ca.crt
        service: grafana.service
        common_name: grafana.home.arpa
        additional_domains: []
        owner: 472
        group: root

      - name: homeassistant
        ca: main
        create_directories: true
        cert: /opt/container-secrets/homeassistant/cert.pem
        key: /opt/container-secrets/homeassistant/key.pem
        cacert: /opt/container-secrets/homeassistant/ca.crt
        service: homeassistant.service
        common_name: homeassistant.home.arpa
        additional_domains: []
        owner: root
        group: root

      - name: influxdb
        ca: main
        create_directories: true
        cert: /opt/container-secrets/influxdb/server.crt
        key: /opt/container-secrets/influxdb/server.key
        service: influxdb.service
        common_name: influxdb
        additional_domains: []
        owner: 1000
        group: root

      - name: restic-backup-1
        ca: restic
        create_directories: true
        cert: /opt/container-secrets/restic-backup-1/ssl_cert.pem
        key: /opt/container-secrets/restic-backup-1/ssl_key.pem
        cacert: /opt/container-secrets/restic-backup-1/ca.pem
        common_name: restic-backup-1.home.arpa
        additional_domains: []
        owner: root
        group: root

      - name: syncthing
        ca: main
        create_directories: true
        cert: /var/containerbind/syncthing/config/https-cert.pem
        key: /var/containerbind/syncthing/config/https-key.pem
        service: syncthing.service
        common_name: syncthing.home.arpa
        additional_domains: []
        owner: 1000
        group: 1000

    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
      clients:
      - name: m1cha-restic
        ca: restic
        create_directories: true
        cert: /home/m1cha/.restic/ssl_cert.pem
        key: /home/m1cha/.restic/ssl_key.pem
        cacert: /home/m1cha/.restic/ca.pem
        combined: /home/m1cha/.restic/ssl_combined.pem
        common_name: m1cha
        owner: m1cha
        group: m1cha
