ungrouped:
  hosts:
    192.168.43.170:
      ansible_user: root
      clients:
      - name: homeserver-restic
        ca: restic
        create_directories: true
        cert: /opt/container-secrets/restic-autobackup/ssl_cert.pem
        key: /opt/container-secrets/restic-autobackup/ssl_key.pem
        cacert: /opt/container-secrets/restic-autobackup/ca.pem
        combined: /opt/container-secrets/restic-autobackup/ssl_combined.pem
        common_name: homeserver
        owner: root
        group: root

      servers:
      - name: bitwarden
        ca: main
        create_directories: true
        cert: /var/containerbind/bitwarden/ssl.crt
        key: /var/containerbind/bitwarden/ssl.key
        service: bitwarden.service
        common_name: bitwarden.home.arpa
        owner: 1000
        group: 1000

      - name: gotify
        ca: main
        create_directories: true
        cert: /opt/container-secrets/gotify/server.crt
        key: /opt/container-secrets/gotify/server.key
        service: gotify.service
        common_name: gotify.home.arpa
        additional_domains:
        - gotify
        owner: root
        group: root

      - name: grafana
        ca: main
        create_directories: true
        cert: /opt/container-secrets/grafana/server.crt
        key: /opt/container-secrets/grafana/server.key
        cacert: /opt/container-secrets/grafana/ca.crt
        service: grafana.service
        common_name: grafana.home.arpa
        owner: 472
        group: root

      - name: homeassistant
        ca: main
        create_directories: true
        cert: /opt/container-secrets/homeassistant/cert.pem
        key: /opt/container-secrets/homeassistant/key.pem
        cacert: /opt/container-secrets/homeassistant/ca.crt
        service: homeassistant.service
        common_name: homeassistant.home.arpa
        owner: root
        group: root

      - name: influxdb
        ca: main
        create_directories: true
        cert: /opt/container-secrets/influxdb/server.crt
        key: /opt/container-secrets/influxdb/server.key
        service: influxdb.service
        common_name: influxdb
        owner: 1000
        group: root

      - name: restic-backup-1
        ca: restic
        create_directories: true
        cert: /opt/container-secrets/restic-backup-1/ssl_cert.pem
        key: /opt/container-secrets/restic-backup-1/ssl_key.pem
        cacert: /opt/container-secrets/restic-backup-1/ca.pem
        common_name: restic-backup-1.home.arpa
        owner: root
        group: root

      - name: syncthing
        ca: main
        create_directories: true
        cert: /var/containerbind/syncthing/config/https-cert.pem
        key: /var/containerbind/syncthing/config/https-key.pem
        service: syncthing.service
        common_name: syncthing.home.arpa
        owner: 1000
        group: 1000

      - name: switch0
        ca: main
        create_directories: true
        cert: /opt/container-secrets/tls-proxy/switch0.crt
        key: /opt/container-secrets/tls-proxy/switch0.key
        cacert: /opt/container-secrets/tls-proxy/ca.crt
        service: tls-proxy.service
        common_name: switch0.home.arpa
        owner: root
        group: root

      - name: switch1
        ca: main
        create_directories: true
        cert: /opt/container-secrets/tls-proxy/switch1.crt
        key: /opt/container-secrets/tls-proxy/switch1.key
        cacert: /opt/container-secrets/tls-proxy/ca.crt
        service: tls-proxy.service
        common_name: switch1.home.arpa
        owner: root
        group: root

      - name: switch2
        ca: main
        create_directories: true
        cert: /opt/container-secrets/tls-proxy/switch2.crt
        key: /opt/container-secrets/tls-proxy/switch2.key
        cacert: /opt/container-secrets/tls-proxy/ca.crt
        service: tls-proxy.service
        common_name: switch2.home.arpa
        owner: root
        group: root

      - name: switch3
        ca: main
        create_directories: true
        cert: /opt/container-secrets/tls-proxy/switch3.crt
        key: /opt/container-secrets/tls-proxy/switch3.key
        cacert: /opt/container-secrets/tls-proxy/ca.crt
        service: tls-proxy.service
        common_name: switch3.home.arpa
        owner: root
        group: root

    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ansible_playbook_python}}"
      clients:
      - name: m1cha-restic
        ca: restic
        create_directories: true
        cert: /home/m1cha/.restic/ssl_cert.pem
        key: /home/m1cha/.restic/ssl_key.pem
        cacert: /home/m1cha/.restic/ca.pem
        combined: /home/m1cha/.restic/ssl_combined.pem
        common_name: m1cha
        owner: m1cha
        group: m1cha
