ungrouped:
  hosts:
    192.168.43.170:
      ansible_user: root
      keys:
      - name: homeassistant
        cert: /opt/container-secrets/homeassistant/cert.pem
        key: /opt/container-secrets/homeassistant/key.pem
        cacert: /opt/container-secrets/homeassistant/ca.crt
        service: homeassistant.service
        common_name: homeassistant.home.arpa
        additional_domains: []
        owner: root
        group: root
