ungrouped:
  hosts:
    192.168.43.170:
      ansible_user: root
      keys:
      - name: grafana
        create_directories: true
        cert: /opt/container-secrets/grafana/server.crt
        key: /opt/container-secrets/grafana/server.key
        cacert: /opt/container-secrets/grafana/ca.crt
        service: grafana.service
        common_name: grafana.home.arpa
        additional_domains: []
        owner: 472
        group: root

      - name: homeassistant
        create_directories: true
        cert: /opt/container-secrets/homeassistant/cert.pem
        key: /opt/container-secrets/homeassistant/key.pem
        cacert: /opt/container-secrets/homeassistant/ca.crt
        service: homeassistant.service
        common_name: homeassistant.home.arpa
        additional_domains: []
        owner: root
        group: root

      - name: syncthing
        create_directories: true
        cert: /var/containerbind/syncthing/config/https-cert.pem
        key: /var/containerbind/syncthing/config/https-key.pem
        service: syncthing.service
        common_name: syncthing.home.arpa
        additional_domains: []
        owner: 1000
        group: 1000
