---
- name: Main
  hosts: "{{ hosts | default('ungrouped') }}"
  gather_facts: false
  vars:
    certs_dir: "{{ playbook_dir }}/certs"

  tasks:
    - name: Create certs directory
      delegate_to: 127.0.0.1
      ansible.builtin.file:
        path: "{{ certs_dir }}"
        state: directory
        mode: '0755'

    - name: Run update_key.yml for servers
      when: servers is defined
      ansible.builtin.include_tasks: update_key.yml
      loop: "{{ servers }}"
      vars:
        cert_type: server

    - name: Run update_key.yml for clients
      when: clients is defined
      ansible.builtin.include_tasks: update_key.yml
      loop: "{{ clients }}"
      vars:
        cert_type: client
