---
- name: Main
  hosts: ungrouped
  gather_facts: false
  vars:
    certs_dir: "{{ playbook_dir }}/certs"

  tasks:
    - name: Create certs directory
      delegate_to: 127.0.0.1
      ansible.builtin.file:
        path: "{{ certs_dir }}"
        state: directory
        mode: '0755'

    - name: Run update_key.yml
      ansible.builtin.include_tasks: update_key.yml
      loop: "{{ keys }}"
