#!/bin/bash

set -euo pipefail

exec podman run \
	--userns keep-id \
	--rm \
	-it \
	-v /run/pcscd:/run/pcscd \
	-v "$SSH_AUTH_SOCK:$SSH_AUTH_SOCK" \
	-e "SSH_AUTH_SOCK=$SSH_AUTH_SOCK" \
	-v "$PWD:$PWD" \
	-w "$PWD" \
	ca \
	"$@"
